language: php

php:
  - 7
  - 7.1

sudo: required
dist: precise

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script:
  - php vendor/bin/phpunit -v

after_success:
  - travis_retry php tests/bin/coveralls.phar
